- hosts: master
  vars:
    benchmarks: --tcp_maerts --tcp_rr --tcp_stream
    fname: knb-raw-results
    loutfile: "../{{ fname }}" # break out of the playbook dir
    routfile: "{{ fname }}"
    # Use the node_ip of the first node to connect to for raw benchmarks
    nodeIP: "{{ hostvars[groups['nodes'][0]]['node_ip'] }}"

  tasks:
  - name: node IP
    debug: msg="{{ nodeIP }}"

  - name: check if outfile exists locally
    stat: path={{ loutfile  }}
    register: outl
    delegate_to: localhost

  - name: block playbook if outfile exists locally
    command: /bin/false
    when: outl.stat.exists
    delegate_to: localhost

  - name: check if outfile exists remotely
    stat: path={{ routfile  }}
    register: outr

  - name: block playbook if outfile exists remotely
    command: /bin/false
    when: outr.stat.exists


  - name: copy netperf script
    copy: src=../scripts/knb-run-raw.sh dest=knb-run-raw.sh mode=0777

  - name: run netperf script
    shell:
      cmd: ./knb-run-raw.sh {{ benchmarks }} {{ nodeIP }} > {{ routfile }}

  - name: fetch output
    fetch:
      src: "{{ routfile  }}"
      dest: "{{ loutfile }}"
      flat: yes
